name: Build & Deploy

env:
  cr: "ghcr.io"
  cr_user: ${{ secrets.cr_user }}
  cr_pat: ${{ secrets.cr_pat }}
  image_name: "ghcr.io/momofin/prod-momofin-fe-emet-superadmin:latest"

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v3
      - name: login to container registry
        run: echo ${{ env.cr_pat }} | docker login ${{ env.cr }} -u ${{ env.cr_user }} --password-stdin
      - name: env-filter
      #   env: 
      #     VITE_API_BASE_URL: "https://api-v1.momofin.com/emet_dashboard"
      #     token_storage_key: "${{ secrets.token_storage_key }}"
        run: |
          ls -al deployment/docker/
          chmod +x -R deployment/docker/
          ./deployment/docker/env-filter.sh
      - name: build docker image 
        run: |
          docker build -t $image_name .
          docker push $image_name
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_SSH_KEY }} 
          known_hosts: 'hello-world'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PROD_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: sync
        run: |
          chmod +x -R deployment/k8s/
          rsync -avz deployment/k8s/ ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}:/home/deployer/${{ github.event.repository.name }}
      - name: deploy container
        run: |
          ssh  ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} 'cd /home/deployer/${{ github.event.repository.name }}/ && ./run.sh'